INSERT INTO tb_user(email) VALUES ('maria@gmail.com');
INSERT INTO tb_user(email) VALUES ('joao@gmail.com');
INSERT INTO tb_user(email) VALUES ('ana@gmail.com');
INSERT INTO tb_user(email) VALUES ('lucia@gmail.com');
INSERT INTO tb_user(email) VALUES ('joaquim@gmail.com');

INSERT INTO tb_livro(score, count, title, image) VALUES (4.5, 2, 'O Poder do Habito', 'https://images-na.ssl-images-amazon.com/images/I/81XTXQEVPlL.jpg');
INSERT INTO tb_livro(score, count, title, image) VALUES (5, 5, '12 Doze Regras para Vidas', 'https://images-na.ssl-images-amazon.com/images/I/51DSFiydE-L.jpg');
INSERT INTO tb_livro(score, count, title, image) VALUES (5, 5, 'Alem da Ordem_ Mais 12 Regras para Vida', 'https://images-na.ssl-images-amazon.com/images/I/41K68N4kydS._SX352_BO1,204,203,200_.jpg');
INSERT INTO tb_livro(score, count, title, image) VALUES (0, 0, 'O Pequeno Principe', 'https://images-na.ssl-images-amazon.com/images/I/419ebAR2eeL._SX346_BO1,204,203,200_.jpg');
INSERT INTO tb_livro(score, count, title, image) VALUES (0, 0, 'Think Like a Monk', 'https://images-na.ssl-images-amazon.com/images/I/71ru1Xg+VyL.jpg');
INSERT INTO tb_livro(score, count, title, image) VALUES (0, 0, 'O Investidor Inteligente', 'https://m.media-amazon.com/images/I/41BKXHTRddL.jpg');
INSERT INTO tb_livro(score, count, title, image) VALUES (0, 0, 'Como Steve Jobs virou Steve Jobs', 'https://images-na.ssl-images-amazon.com/images/I/71Y-5u2AL1L.jpg');
INSERT INTO tb_livro(score, count, title, image) VALUES (0, 0, 'Greenlights', 'https://m.media-amazon.com/images/I/41JMH+5JNCL.jpg');
INSERT INTO tb_livro(score, count, title, image) VALUES (0, 0, 'Talk Like Ted', 'https://images-na.ssl-images-amazon.com/images/I/61MVvFfrSLL.jpg');
INSERT INTO tb_livro(score, count, title, image) VALUES (0, 0, 'How to Win Friends & Influence People', 'https://images-na.ssl-images-amazon.com/images/I/619Gn-+VNQL.jpg');
INSERT INTO tb_livro(score, count, title, image) VALUES (0, 0, 'War And Peace', '');
INSERT INTO tb_livro(score, count, title, image) VALUES (0, 0, 'The Almanack of Naval Ravikant', 'https://m.media-amazon.com/images/I/31EQXd8E9eL.jpg');
INSERT INTO tb_livro(score, count, title, image) VALUES (0, 0, 'Brain maker', 'https://m.media-amazon.com/images/I/51TspotPhEL.jpg');
INSERT INTO tb_livro(score, count, title, image) VALUES (0, 0, '1984', 'https://images-na.ssl-images-amazon.com/images/I/81EStZoMf7L.jpg');
INSERT INTO tb_livro(score, count, title, image) VALUES (0, 0, 'A Revolucao dos Bichos', 'https://images-na.ssl-images-amazon.com/images/I/91BsZhxCRjL.jpg');
INSERT INTO tb_livro(score, count, title, image) VALUES (0, 0, 'Unlock It', 'https://m.media-amazon.com/images/I/41Bg5CZ+qRL.jpg');
INSERT INTO tb_livro(score, count, title, image) VALUES (0, 0, 'Para Poder Viver', 'https://images-na.ssl-images-amazon.com/images/I/41cq5-qHkyL._SX335_BO1,204,203,200_.jpg');
INSERT INTO tb_livro(score, count, title, image) VALUES (0, 0, 'How To Be a Conservative', 'https://images-na.ssl-images-amazon.com/images/I/71qGEPiaIZL.jpg');
INSERT INTO tb_livro(score, count, title, image) VALUES (0, 0, 'Arquipelogo Gulag', 'https://images-na.ssl-images-amazon.com/images/I/61AsHoJj7CL.jpg');
INSERT INTO tb_livro(score, count, title, image) VALUES (0, 0, 'Harry Potter e a Pedra Filosofal', 'https://images-na.ssl-images-amazon.com/images/I/81ibfYk4qmL.jpg');
INSERT INTO tb_livro(score, count, title, image) VALUES (0, 0, 'Alice no País das Maravilhas', 'https://images-na.ssl-images-amazon.com/images/I/61AD--JL1KL._SX331_BO1,204,203,200_.jpg');
INSERT INTO tb_livro(score, count, title, image) VALUES (0, 0, 'Animais Fantásticos e Onde Habitam', 'https://images-na.ssl-images-amazon.com/images/I/91WjGu9-YDL.jpg');
INSERT INTO tb_livro(score, count, title, image) VALUES (0, 0, 'Business Adventures', 'https://images-na.ssl-images-amazon.com/images/I/81wyS0Xt02L.jpg');
INSERT INTO tb_livro(score, count, title, image) VALUES (0, 0, 'Can Hurt Me', 'https://images-na.ssl-images-amazon.com/images/I/614KqBMkryL.jpg');
INSERT INTO tb_livro(score, count, title, image) VALUES (0, 0, 'Churchill The Power of Words', 'https://images-na.ssl-images-amazon.com/images/I/51UcCMeIJhL.jpg');
INSERT INTO tb_livro(score, count, title, image) VALUES (0, 0, 'The 5 Second Rule', 'https://m.media-amazon.com/images/I/51abdHvm+EL.jpg');
INSERT INTO tb_livro(score, count, title, image) VALUES (0, 0, 'The 7 habits of Highly Effective People', 'https://images-na.ssl-images-amazon.com/images/I/51hV5vGr4AL.jpg');
INSERT INTO tb_livro(score, count, title, image) VALUES (0, 0, 'Why We Sleep', 'https://m.media-amazon.com/images/I/51WOq1TRGdL.jpg');
INSERT INTO tb_livro(score, count, title, image) VALUES (0, 0, 'Man Search for Meaning', 'https://m.media-amazon.com/images/I/41s4xJZlEYL.jpg');

INSERT INTO tb_score(movie_id, user_id, value) VALUES (1, 1, 5.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (1, 2, 4.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 1, 3.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 2, 3.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 3, 4.0);